FROM golang:1.22

ARG USERNAME=admin
ARG USER_UID=1000
ARG USER_GID=984

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    # Add sudo support.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    # Install ffmpeg.
    && apt-get install -y ffmpeg

USER $USERNAME
