from contextlib import asynccontextmanager

from fastapi import APIRouter, FastAPI
from fastapi.openapi.utils import get_openapi
from pymongo import AsyncMongoClient
from slowapi import _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded

from v2g.core.config import settings
from v2g.modules.auth.routes import router as router_login
from v2g.modules.conversions.models import ConversionWebhookBody
from v2g.modules.conversions.routes import router as router_conversion
from v2g.modules.users.routes import router as router_user
from v2g.rate_limiter import limiter

router = APIRouter()
router.include_router(router_login, prefix='/auth', tags=['Authentication'])
router.include_router(router_user, prefix='/users', tags=['User'])
router.include_router(router_conversion, prefix='/conversions', tags=['Conversion'])


@asynccontextmanager
async def lifespan(app: FastAPI):
    async with AsyncMongoClient(
        host=settings.mongodb.host,
        port=settings.mongodb.port,
    ) as mongo_client:
        yield {'mongo_client': mongo_client}


app = FastAPI(lifespan=lifespan)

app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

app.include_router(router, prefix=settings.api_v1_str)


@app.webhooks.post(
    path='conversion-done',
    summary='Notification of conversion completion',
)
def conversion_done(body: ConversionWebhookBody):
    """
    Triggered when a conversion process completes. Sends an HTTP POST request
    to the URL that you provide when create a conversion.
    Your server must respond with a 2xx code to acknowledge the webhook.
    """


def custom_openapi():
    if app.openapi_schema:
        return app.openapi_schema

    openapi_schema = get_openapi(
        title='Video to GIF',
        version='0.1.0',
        summary='Create a user. Get a token. Run conversion of a short video to a gif. Wait the conversion to finish polling the conversion info.',
        routes=app.routes,
        webhooks=app.webhooks.routes,
    )

    # Assign prettier titles to some components with autogenerated names.
    for component_name, component_schema in openapi_schema['components']['schemas'].items():
        if component_name == 'Body_convert_video_conversion__post':
            component_schema['title'] = 'ConversionCreate'
        elif component_name == 'Body_get_access_token_login_access_token__post':
            component_schema['title'] = 'TokenCreate'

    app.openapi_schema = openapi_schema
    return app.openapi_schema


app.openapi = custom_openapi
